<a href="https://colab.research.google.com/github/sitirahmalatuconsina19/sitirahma_dm/blob/main/AlgoritmaC45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/hargarumah.csv')
df

        harga  luas  kasur  km
0    13300000  7420      4   2
1    12250000  8960      4   4
2    12250000  9960      3   2
3    12215000  7500      4   2
4    11410000  7420      4   1
..        ...   ...    ...  ..
540   1820000  3000      2   1
541   1767150  2400      3   1
542   1750000  3620      2   1
543   1750000  2910      3   1
544   1750000  3850      3   1

[545 rows x 4 columns]

In [3]:
df.isnull().sum()

harga    0
luas     0
kasur    0
km       0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   harga   545 non-null    int64
 1   luas    545 non-null    int64
 2   kasur   545 non-null    int64
 3   km      545 non-null    int64
dtypes: int64(4)
memory usage: 17.2 KB

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
for column in df:
  if df[column].dtypes == object:
    df[column] = le.fit_transform(df[column])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   harga   545 non-null    int64
 1   luas    545 non-null    int64
 2   kasur   545 non-null    int64
 3   km      545 non-null    int64
dtypes: int64(4)
memory usage: 17.2 KB

In [9]:
df

        harga  luas  kasur  km
0    13300000  7420      4   2
1    12250000  8960      4   4
2    12250000  9960      3   2
3    12215000  7500      4   2
4    11410000  7420      4   1
..        ...   ...    ...  ..
540   1820000  3000      2   1
541   1767150  2400      3   1
542   1750000  3620      2   1
543   1750000  2910      3   1
544   1750000  3850      3   1

[545 rows x 4 columns]

In [10]:
df.describe()

              harga          luas       kasur          km
count  5.450000e+02    545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239
std    1.870440e+06   2170.141023    0.738064    0.502470
min    1.750000e+06   1650.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000

In [33]:
df = df.drop(['harga'], axis=1)

In [34]:
x = df.drop(['km'], axis=1)
y = df['km']

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2)

In [36]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=500, max_depth=None,
                               min_samples_split=2,
                               min_samples_leaf=1,
                               min_weight_fraction_leaf=0,
                               max_leaf_nodes=None,
                               min_impurity_decrease=0)

In [37]:
clf = model.fit(x_train, y_train)

In [38]:
model.score(x_test, y_test)

0.7522935779816514

In [18]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

In [39]:
from sklearn.tree import export_graphviz
import graphviz

tree_data = export_graphviz (model, out_file = None,
                                feature_names = x.columns,
                                class_names = ['0','1'],
                                filled = True)

In [41]:
graph = graphviz.Source(tree_data)
graph.view

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Confusion Matrix
y_pred = model.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print("CONFUSION MATRIX")
print(cm)
akurasi=classification_report(y_test,y_pred)
print("ACCURACY C4.5")
print("Accuracy :", akurasi)
akurasi=accuracy_score(y_test,y_pred)
print('Tingkat akurasi : {:.2%}'.format(akurasi))

CONFUSION MATRIX
[[73  6  0]
 [18  9  0]
 [ 2  1  0]]
ACCURACY C4.5
Accuracy :               precision    recall  f1-score   support

           1       0.78      0.92      0.85        79
           2       0.56      0.33      0.42        27
           3       0.00      0.00      0.00         3

    accuracy                           0.75       109
   macro avg       0.45      0.42      0.42       109
weighted avg       0.71      0.75      0.72       109

Tingkat akurasi : 75.23%

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))