<a href="https://colab.research.google.com/github/sitirahmalatuconsina19/sitirahma_dm/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [2]:
data = pd.read_csv('/content/hargarumah.csv')
data.head()

      harga  luas  kasur  km
0  13300000  7420      4   2
1  12250000  8960      4   4
2  12250000  9960      3   2
3  12215000  7500      4   2
4  11410000  7420      4   1

In [3]:
print(data.isnull().sum())

harga    0
luas     0
kasur    0
km       0
dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   harga   545 non-null    int64
 1   luas    545 non-null    int64
 2   kasur   545 non-null    int64
 3   km      545 non-null    int64
dtypes: int64(4)
memory usage: 17.2 KB

In [5]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [6]:
for column in data:
  if data[column].dtypes == object:
    data[column] = enc.fit_transform(data[column])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   harga   545 non-null    int64
 1   luas    545 non-null    int64
 2   kasur   545 non-null    int64
 3   km      545 non-null    int64
dtypes: int64(4)
memory usage: 17.2 KB

In [8]:
data

        harga  luas  kasur  km
0    13300000  7420      4   2
1    12250000  8960      4   4
2    12250000  9960      3   2
3    12215000  7500      4   2
4    11410000  7420      4   1
..        ...   ...    ...  ..
540   1820000  3000      2   1
541   1767150  2400      3   1
542   1750000  3620      2   1
543   1750000  2910      3   1
544   1750000  3850      3   1

[545 rows x 4 columns]

In [9]:
data.describe()

              harga          luas       kasur          km
count  5.450000e+02    545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239
std    1.870440e+06   2170.141023    0.738064    0.502470
min    1.750000e+06   1650.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000

In [11]:
trs_data = data.drop(columns='luas')
trs_data.head()

      harga  kasur  km
0  13300000      4   2
1  12250000      4   4
2  12250000      3   2
3  12215000      4   2
4  11410000      4   1

In [18]:
lbl_data = data['km']
lbl_data.head()

0    2
1    4
2    2
3    2
4    1
Name: km, dtype: int64

In [19]:
x_train,x_test,y_train,y_test=train_test_split(trs_data,lbl_data,test_size=0.9,random_state=500)
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [20]:
print('accuracy of Naive bayes Kontinu classifier on test set: {:.2f}'.format(classifier.score(x_test,y_test)))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
hasilpengujian = classification_report(y_test,y_pred)
print(hasilpengujian)

accuracy of Naive bayes Kontinu classifier on test set: 0.79
[[336  20   5   0]
 [ 70  50   0   0]
 [  4   5   0   0]
 [  0   1   0   0]]
0.7861507128309573
              precision    recall  f1-score   support

           1       0.82      0.93      0.87       361
           2       0.66      0.42      0.51       120
           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00         1

    accuracy                           0.79       491
   macro avg       0.37      0.34      0.35       491
weighted avg       0.76      0.79      0.77       491

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))